### ISSUE TITLE
All applications use the same generated DLL

### ISSUE THREAD

**Issue by Slion** [Slion/VirtualDesktop#12]
All applications using VirtualDesktop use the same generated DLL from the app data folder.
We should store it on a path specific to the running application to avoid conflicts.

**Comment by Slion** [comment]
Actually I don't think this is true. It might already be working properly.

**Comment by Slion** [comment]
This is definitely not an issue for packaged applications such as [Taskbar](https://slions.net/resources/taskbar.13/) where the generated assembly lands in such path:
`C:\Users\micro\AppData\Local\Packages\Slions.TaskbarTest_aarv4tknj59mw\LocalCache\Local\slions.net\VirtualDesktop\assemblies`

However I wonder if this could be an issue for non-packaged applications such as our demo sample where the generated assembly land in such path:
`C:\Users\micro\AppData\Local\slions.net\VirtualDesktop\assemblies`

**Comment by mzomparelli** [comment]
I think you're right every app would use the same dll, why would there be conflicts?

Why not generate the DLL next to the existing one where the users exe is? That way each app has to generate their own.

**Comment by mzomparelli** [comment]
I don't like it going to appdata personally

**Comment by mzomparelli** [comment]
I'm afraid generating next to the existing dll might not be a good idea if the user wants to create a single exe with no attached dlls. The original dll can be injected into the exe but the generated dll would be exposed. Might not be so bad if it removed the generated dll when the app shutdown.

**Comment by mzomparelli** [comment]
I think it's fine the way it is and I don't think apps using the same dll will cause a conflict.

**Comment by Slion** [comment]
I'm not even sure it works at all when having multiple applications using it as it can lead to the following exception. I got it when running an application using it from Visual Studio and trying to launch the demo from Visual Studio too. Looks like it just fails to overwrite that runtime generated DLL:
```
System.IO.IOException
  HResult=0x80070020
  Message=The process cannot access the file 'C:\Users\micro\AppData\Local\slions.net\VirtualDesktop\assemblies\VirtualDesktop.10.0.26100.1742.generated.dll' because it is being used by another process.
  Source=System.Private.CoreLib
  StackTrace:
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Create(String path)
   at Roslyn.Utilities.FileUtilities.CreateFileStreamChecked(Func`2 factory, String path, String paramName)
   at Microsoft.CodeAnalysis.FileSystemExtensions.Emit(Compilation compilation, String outputPath, String pdbPath, String xmlDocPath, String win32ResourcesPath, IEnumerable`1 manifestResources, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpFileSystemExtensions.Emit(CSharpCompilation compilation, String outputPath, String pdbPath, String xmlDocumentationPath, String win32ResourcesPath, IEnumerable`1 manifestResources, CancellationToken cancellationToken)
   at WindowsDesktop.Interop.ComInterfaceAssemblyBuilder.Compile(IEnumerable`1 sources) in S:\Dev\GitHub\Slion\VirtualDesktop\src\VirtualDesktop\Interop\ComInterfaceAssemblyBuilder.cs:line 193
   at WindowsDesktop.Interop.ComInterfaceAssemblyBuilder.CreateAssembly() in S:\Dev\GitHub\Slion\VirtualDesktop\src\VirtualDesktop\Interop\ComInterfaceAssemblyBuilder.cs:line 153
   at WindowsDesktop.Interop.ComInterfaceAssemblyBuilder.GetAssembly() in S:\Dev\GitHub\Slion\VirtualDesktop\src\VirtualDesktop\Interop\ComInterfaceAssemblyBuilder.cs:line 43
   at WindowsDesktop.VirtualDesktop.InitializeCore() in S:\Dev\GitHub\Slion\VirtualDesktop\src\VirtualDesktop\VirtualDesktop.system.cs:line 132
   at WindowsDesktop.VirtualDesktop.InitializeIfNeeded() in S:\Dev\GitHub\Slion\VirtualDesktop\src\VirtualDesktop\VirtualDesktop.system.cs:line 120
   at WindowsDesktop.VirtualDesktop.Configure() in S:\Dev\GitHub\Slion\VirtualDesktop\src\VirtualDesktop\VirtualDesktop.system.cs:line 99
   at VirtualDesktopShowcase.MainWindow.InitializeComObjects() in S:\Dev\GitHub\Slion\VirtualDesktop\samples\VirtualDesktop.Showcase\MainWindow.xaml.cs:line 34
   at VirtualDesktopShowcase.MainWindow..ctor() in S:\Dev\GitHub\Slion\VirtualDesktop\samples\VirtualDesktop.Showcase\MainWindow.xaml.cs:line 29
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
```
